version: '3.2'

services:
  backend:
    build: ./docker
    image: admin-school-backend
    container_name: backend
    ports:
      - 8080:80  
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/var/www/admin-school 
    networks:
       - my-network 

  frontend:
    build: ./docker
    image: admin-school-frontend
    container_name: frontend
    ports:
      - 8081:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/var/www/admin-school
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    networks:
       - my-network 
         
  dbyii2:
    build: ./docker/mysql          
    container_name: mysql-container
    restart: always    
    ports:
      - 23306:3306
    environment:    
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: admin-school
        MYSQL_USER: admin-school
        MYSQL_PASSWORD: admin-school   
    volumes:
       - ./my-db:/var/lib/mysql:rw
    networks:
       - my-network              
volumes:
  my-db: {}
networks:
  my-network:
    name: mysql_net
    driver: bridge


 

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret